### ISSUE TITLE
Include click target in outclick event

### ISSUE THREAD

**Issue by happyleavesaoc** [babakfp/svelte-outclick#14]
It would be nice if the dispatched `outclick` event included the click target, much like a normal `click` event. Sometimes I want to take specific actions depending on where the outclick landed.

**Comment by babakfp** [comment]
Hi 👋
Good to know. I'll implement it today/tomorrow and publish a new release.

**Comment by babakfp** [comment]
All done.
Thank you for your interest.
I'll fix up some things and release a new version on NPM soon.

**Comment by babakfp** [comment]
I forgot to say that version `3.7.1` was released.
This new version has a breaking change. I mistakenly only bumped the minor version.
You can read the [CHANGELOG](https://babakfp.ir/docs/svelte-outclick/changelog).

**Comment by happyleavesaoc** [comment]
Thanks!
