### ISSUE TITLE
Mouseclick doesn't work on mobile - pointerdown does

### ISSUE THREAD

**Issue by iSteeb** [babakfp/svelte-outclick#6]
Easy issue, easy fix.

**Comment by babakfp** [comment]
Hi there
What do you mean? Can you screen record the problem or something like that, please?
Thanks

**Comment by iSteeb** [comment]
Sorry, I did a pretty poor job of that post.

I used your code for a project and it worked perfectly on a desktop, but nothing would happen on my mobile (safari iOS).  Your demo reproduces the bug on the same browser - no action occurs from an out click.

Bit of research suggested mousedown is specific to mice, touchdown is specific to touch screens and a more recent not-fully-supported (i believe only since safari 13 for safari) event is on pointerdown which captures both mice and touch.

Made the change for my project and can confirm that it works as intended.

**Comment by babakfp** [comment]
Ops, I forgot to ask you to check out the new version. Please check out the new version and if all was fine, feel free to close the issue.
