### ISSUE TITLE
Can we have typescript support?

### ISSUE THREAD

**Issue by roshitaStudentPack** [babakfp/svelte-outclick#8]
I was working with something i used this package and i was unable to use it because of not having support of typescript.
Currently i have just copied your code and made my own component.

**Comment by babakfp** [comment]
Hey
I remember adding TS support but I don't know why I didn't publish it. I guess I'll try it again and let you know.
Thanks

**Comment by babakfp** [comment]
Added TS support in v3.4.0 🎉👏

**Comment by babakfp** [comment]
Added TS support in v3.4.0 🎉👏
